### ISSUE TITLE
worker_results Array or Not?

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq#101]
**Query on Stoq**
The vtmis-search plugin's deep dispatcher tests for worker data like...
`'iocextract' in payload.worker_results`
...but the worker "scan" function tests like...
```
for worker_result in payload.worker_results:
            if 'iocextract' in worker_result:
```

In my custom deep-dispatcher plug-in I'm unable to test like the vtmis-search plugin's deep-dispatcher because my worker_results is an array of objects, so it seem to require the later style to do so, or...
`'iocextract' in payload.worker_results[0]`

What determines if worker_results is an array and won't support the simple "in" test?

Is it just multiple payloads (i.e. from a compressed file extract), and if so how can the vtmis-search plug-in presume it won't be an array (or work at all, even analysis without multiple payloads seems to be an array of objects for me)?

**Comment by Kolano** [comment]
Er, nevermind (at least I think). My issue wasn't with the test, but with trying to get data out later i.e.
`worker_results['hash']['sha256']`
vs
`worker_results[0]['hash']['sha256']`

**Comment by Kolano** [comment]
Sorry for the back and forth on this, I thought it was working out for a bit, but it was just that this simple test was consistently failing against payloads with hash data:
`'hash' in payload.worker_results`

**Comment by Kolano** [comment]
OK, once I got my deep-dispatcher to actually do something I can see that the workers it adds aren't merged in to the original array, instead getting tacked on as additional objects...

```
"workers": [
{
    "trid": {
        "EXE": {
            "likely": "2.6%",
            "type": "DOS Executable Generic (2000/1)"
        }
    },
    "mimetype": {
        "mimetype": "application/x-dosexec"
    },
    "hash": {
        "sha256": "135be7803f70c11933f6a846d0c520debf8d274962f50985d910529ddb46ee8d",
        "md5": "f05c76a9fce6694fab7793b9914d5162",
        "sha1": "7a5b77e260e1e10094306c3ac44a3e756820658e"
    }
},
{
    "prior-analysis": {
        "analyzed": true
    }
}
],
```

That seems to make it a pain to test for workers and I'm still confused about how the vtmis-search deep-dispatcher works out then.

**Comment by mlaferrera** [comment]
That was an error in the `vtmis-search` plugin, which has been corrected.

`payload.worker_results` should always be a `List` of `Dicts`.

As for `payload.plugins_run`, that is a `Dict` that contains the keys `workers` and `archivers`. For `workers`, it is a `List` of `List`'s. Each index in the list represents the round of dispatching that the plugin was run in. For example, the first round of scanning used `iocextract` and the second round of scanning used `vtmis-search`.

**Comment by Kolano** [comment]
OK, glad to help you identify that.

With regards to testing for workers I found this to be a nice 1 line solution...
`if any("hash" in plugins for plugins in payload.worker_results):`
...though possibly not appropriate for more complex checks (i.e. for multiple plugins).

**Comment by mlaferrera** [comment]
Glad to hear you were able to get it working and thanks for the feedback again. I'll go ahead and close this issue now that it's been resolved.

**Comment by Kolano** [comment]
Looks like you may have forgotten the break on the deep dispatcher.
