### ISSUE TITLE
Preserve .stoq [options] Through Upgrade

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq#102]
**Is your feature request related to a problem? Please describe.**
.stoq [options] are not preserved through upgrades.

**Describe the solution you'd like**
It would be nice to transition matching key values from the [options] section of plugin.stoq files during --upgrade installs; ignoring keys that no longer appear in the new file. Perhaps only if given an additional command line option to avoid prompting.

**Describe alternatives you've considered**
Notify when [options] values will be purged/overwritten by an upgrade.

**Comment by mlaferrera** [comment]
As of v2.0.3, plugin options are now permitted in `stoq.cfg` and will take precedence over settings in the plugin's configuration file. You can read more on how to do that [here](https://stoq-framework.readthedocs.io/en/latest/dev/plugin_overview.html#stoq-cfg). We don't have any plans to ensure plugin options are maintained across upgrades.

**Comment by Kolano** [comment]
Ah, sorry, missed that revision with 2.0.3.

Where is stoq.cfg read from by default? The only instance of it in my install is...
`/home/user/.stoq/.venv/lib/python3.6/site-packages/stoq/tests/data/stoq.cfg`

**Comment by Kolano** [comment]
Never mind, found the other documentation here...
https://github.com/PUNCH-Cyber/stoq/blob/ab78a09594e1474ef6ef2e2aa07a35a033079b31/docs/gettingstarted.rst
...might want to interlink those.

**Comment by Kolano** [comment]
Thanks for the quick action here, looks like your syntax on the link was a bit off though.
