### ISSUE TITLE
Deeper Dispatchers?

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq#103]
**Is your feature request related to a problem? Please describe.**
From the documentation...

> deep dispatchers can be run 0 to N times per payload

Do I need to handle things specially in my deep dispatchers to handle multiple iterations?

Currently it seems my custom deep dispatcher only does one initial round of dispatching. I expected after it's dispatched set of workers competed that the payload would run through my deep dispatcher again allowing it to use data from any of the previous workers, until the DeepDispatcherResponse was returned without additions.

The deep dispatchers basic outline is...

- Check for expected initial workers
- Pull data points from each relevant worker encountered
- Check for prior analysis: add prior-analysis worker, or...
  - Check for decompressable type: add decompress worker
  - Check for VT scannable type: add vtmis-search worker
  - Check vtmis-search results indicating unknown file: add sandbox worker
- Return DeepDispatcherResponse

It seems after the initial run that assigns payloads to the decompress / vtmis-search plugins, things never come around again to allow for analysis with the vtmis-search / decompress results included (at least since decompress mainly launches other payloads it's not critical).

I can provide code, but would need to pare it down first to avoid requiring/using my other custom workers.

**Describe the solution you'd like**
Multiple iterations of deep dispatchers to occur by default, or the mechanism to cause repeated iterations documented.

**Additional context**
This may actually be a bug with the way deep dispatchers are handled, but I wasn't sure.

**Comment by Kolano** [comment]
I also tried upping...
`max_recursion: 5`
...in stoq.cfg, to no effect.

**Comment by mlaferrera** [comment]
`max_dispatch_passes` is the setting you are looking for. By default it is set to `1` to prevent infinite repetitions.

**Comment by Kolano** [comment]
Ah, OK. You might want to make that clearer on...
https://stoq-framework.readthedocs.io/en/latest/dev/deepdispatchers.html / 
https://github.com/PUNCH-Cyber/stoq/blob/53db78149a20bd21b13b765eccddc8955f43ab11/stoq/plugins/deep_dispatcher.py
...the current wording makes it sound as though it is limitless by default, and one must set that to limit it.
