### ISSUE TITLE
stoq doesn't provide user feedback if configuration is nonexistent

### ISSUE THREAD

**Issue by jakubgs** [PUNCH-Cyber/stoq#107]
## Describe the bug
My config file doesn't seem to be loaded at all.

## To Reproduce
I have `source_dir` for `dirmon` defined in my `/opt/stoq/stoq.conf`(my `STOQ_HOME` is set to `/opt/stoq`):
```ini
[dirmon]
source_dir: "/opt/stoq/Maildir/new"
```
But when i run:
```bash
/opt/stoq/venv/bin/stoq run -a smtp -P dirmon -C redis-queue
```
I get back:
```
...
  File "/opt/stoq/plugins/dirmon/dirmon.py", line 49, in __init__
    f"Source directory not defined or doesn't exist: '{self.source_dir}'"
stoq.exceptions.StoqPluginException: Source directory not defined or doesn't exist: 'None
```
~~I even tried specifying `--plugin-opts dirmon:source_dir=/opt/stoq/Maildir/new` explicitly but that did nothing as well.~~ This works.

## Expected behavior
Config contents are not ignored.

## Client
```
Ubuntu 18.04.2 LTS
```
```
stoQ :: v2.0.4 :: an automated analysis framework
```

**Comment by jakubgs** [comment]
I added this:
```python
print("sections: {}".format(config.sections()))
```
After this:
https://github.com/PUNCH-Cyber/stoq/blob/bbeef9954a4f5e815760dd6b28c3f623fd778658/stoq/core.py#L382-L384
And my result is this:
```
sections: []
```
And then I added another to check config path and got back:
```
config_file: /opt/stoq/stoq.cfg
```
Which makes the issue obvious:
```
 $ ls -l /opt/stoq/stoq.cfg
ls: cannot access '/opt/stoq/stoq.cfg': No such file or directory
 $ ls -l /opt/stoq/stoq.conf 
-rw-r--r-- 1 stoq staff 486 Apr  8 07:37 /opt/stoq/stoq.conf
```
My config file had wrong extension, `conf` instead of `cfg`.

I really think `stoq` should show a warning message saying `No config file found at "/opt/stoq/stoq.cfg", using defaults.`, so as to make it clear to the user what's happening.

**Comment by mlaferrera** [comment]
Thanks, @jakubgs. I just pushed up a change that will display feedback if the configuration file doesn't exist while using stoQ from the command line.
