### ISSUE TITLE
Plugin logging

### ISSUE THREAD

**Issue by ytreister** [PUNCH-Cyber/stoq#110]
stoQ allows you to set the log_level for the core stoQ engine.  First off, the documentation is lacking and does not make it clear what options are available (INFO, DEBUG, ETC.).  It seems like this log is really only for logging activity that the core stoQ framework logs and not for logging plugin activity.  There is only one public plugin that I was able to find that has some logging, vtmis-filefeed.  It appears to log to the same logger that the core stoq framework logs to.

What is the recommended way for plugins to log using the stoQ framework?  It seems like most plugins simply add errors to the WorkerResponse object.

I was thinking of creating a utility for creating compartmented logs.  I wanted separate logs for each payload that gets added to the queue from a provider plugin (and all children of that payload).  If I tried to use the existing log framework that stoQ uses, I would not be able to easily differentiate information provided to the log.

**Comment by mlaferrera** [comment]
Hi @ytreister -- 

Currently the recommended method is to use the same logger as `Stoq()` uses. A good example of this is what you already mentioned, which is the vtmis-filefeed plugin. 

Are you looking to have multiple log files? For example, one for the core framework (`stoq.log`) and then one for each plugin (i.e., `yara-plugin.log`, `exif-plugin.log`, etc...). Or, are you just looking for a better way for logged events to show up in `stoq.log`?

**Comment by ytreister** [comment]
I would want a separate log file for each item that gets ingested.  I consider each item added to the stoQ queue as an "exam".  An "exam" may produce several artifacts, children files, etc.  I would want to be able to follow the scanning, dispatching, recursive carving out of the "exam" and be able to isolate the activity based on the "exam".  I view the stoq.log as the master log for a stoq runner.  A stoq runner may be processing multiple "exams" in parallel.  So the stoq.log might only have logs from a provider plugin and each item added to the stoQ queue would have their own log...

Does that make sense?

**Comment by mlaferrera** [comment]
Hi @ytreister -- sorry for the delay. Are you looking to do this in a production environment, or for debug/testing purposes. The reason I ask is that this would be pretty expensive from an IO perspective to essentially create a new logger context with each "exam". I don't know if the core stoq framework is the best place for this. 

Would improving the way stoQ stores and handles errors be a potential solution? For instance, right now errors are a list of key/value pairs. It is difficult to identify exactly where in the pipeline an error occurred if a single plugin was run more than once. We are currently looking at ways to improve this in stoQ v3 and would love your input if this is something you would find useful.

**Comment by ytreister** [comment]
Thanks for getting back to me, @mlaferrera 
I would want this in a production environment.  The reason is that new files submitted in production env will often find corner cases that we did not imagine during dev/testing.  Imagine a user submits files to our stoQ instance, reviews the output and then asks a question such as: Why did AVs not detect malware?  Why didn't peinfo give rich header information?  Why didn't I see any string information for my files?

With logs I would be able to answer questions with answers like AV did not run because OPSWAT MetaDefender had an outage at the time of the exam.  The peinfo did not provide rich header information because the PE was corrupt.  We will update peinfo to deal with these situations better in the future  You did not see string information because our YARA rule was too specific, and did not dispatch that string parser worker that you were expecting...

I understand if you do not think that this makes sense for the core stoQ framework.  We were thinking of writing a child of WorkerPlugin class that would log to the exam specific log when the scan method is entered and exited.  Each worker plugin would then have access to the exam specific logger and could log things at different levels (info, debug, etc.)  This way we would be able to find out the where, when, who, why a worker failed.

Regarding your other question, I do think it would be better if stoQ had a more consistent and informative way of storing errors.  Perhaps there could be a standard method that could be called:
self.save_error(error_message) which would save the error_message in addition to some other important meta-data that identifies:
* scan_id
* payload_id
* timestamp
* worker_name

**Comment by mlaferrera** [comment]
Hey @ytreister -- Thanks for providing the feedback. I've been working on v3 of stoQ, and just merged in new functionality for improving the way stoQ logs error messages from plugins. Essentially there is a new `Error()` class that gets appended to the new `Request().errors` object. For a little bit of background, the `Request()` class is made available to each dispatcher and worker plugin. This object stores all results from each plugin, the original request metadata, as well as all errors from each plugin.

Essentially you can now create a new error with `Error(plugin_name, error_msg, payload_id)`, and return that with your plugin response object (i.e., `return WorkerResponse(response, errors)`. For example, the below would be in your plugin:

```
errors = [Error(plugin_name='my_plugin', error='this failed', payload_id=payload.payload_id)]
return WorkerResponse(my_response, errors=errors)
```

This isn't a final implementation, so if you have ideas on how it could be improved please let me know.

As for your feedback on a logger within plugins, I'm still thinking that over how to best implement that. I think I have an idea for how a logger could be made universally available within each plugin, which should also help get you closer to logging in individual log files per payload. Once I get some of that written, I will let you know in this thread.

**Comment by ytreister** [comment]
Hi @mlaferrera,
I am looking forwar to seeing how your logger would work.

As far as your Error class goes.  I think it is a good idea to standardize how errors get reported.

I am not sure, but maybe the error can have a little bit more.  Maybe instead of just self.error, there could be 
* title (this could be optional and users might come up with short names for the error)
* description (this would be detailed string)
* category (could default to generic, but users might want to set it to things like authentication, network, system, etc.)
* stacktrace (optionally can be included if the error is a caught exception)
  Maybe add an instance variable named error_type which could default to 'ERROR'

**Comment by mlaferrera** [comment]
Thanks for the feedback @ytreister.

From a core stoQ perspective, I'm not a huge fan of adding a lot to it that may complicate error handling. Ideally I'd like to keep it as simple as possible to handle the main error cases that would be encountered within stoQ.

With that said, one of the benefits of creating the `Error` class is you can now subclass it to add in your own objects as desired. For example, in your use case above, you'd be able to do:

```
from stoq import Error

class MyPluginError(Error):
    def __init__(
        self, 
        plugin_name: str, 
        description: str, 
        payload_id: Optional[str] = None, 
        title: Optional[str] = None, 
        category: Optional[str] = None, 
        stacktrace: Optional[str] = None
    ) -> None:
        self.plugin_name = plugin_name
        self.description = description
        self.payload_id = payload_id
        self.title = title
        self.category = category
        self.stacktrace = stacktrace
```

I hope this helps!

**Comment by ytreister** [comment]
OK, sounds like a great plan.
