### ISSUE TITLE
Provide a way for workers to create files that won't get scanned

### ISSUE THREAD

**Issue by chemberger** [PUNCH-Cyber/stoq#114]
**Is your feature request related to a problem? Please describe.**

When using stoQ as an augmentation tool for manual analysis, I sometimes want stoQ to generate files that are not intended for further analysis. Examples:
* full pdf rapport from a sandbox
* plaso timeline that would be too voluminous to include in the results, and that I could simply download and reinject in other tools
* beautified js

**Describe the solution you'd like**

* Add a flag in PayloadMeta just like dispatch_to that says not to run the default worker on this file. It would be nice to still have a way for special workers to use them (plaso example: have a plugin that analyses it or uploads it to timesketch), but I guess special dispatcher/deepdispatcher or dispatch_to could be used for that effect

**Describe alternatives you've considered**

* Saving it in analysis/result : It could work for some stuff (plaso), but it would make the result bloated and it would make it harder to extract the tool for use outside of stoQ
* Saving it as an extracted payload and letting analysis run: it would create useless or duplicate computation and result, but it could be usefull in some cases (plaso: have a plugin that finds anomalies)
* Archiving it with an out of band archive method in the worker code: defeats the purpose of stoQ
* add a parameter in WorkerResponse for a list of payloads that should just get archived
Those payloads will get logged in the result and dumped by the archiver plugin(s), but won't get reanalyzed: It's another clean solution that I like

**Additional context**

I'm thinking about implementing it myself, so this issue is more about discussing if core stoQ is interested in this feature, and what the best way to implement it is.

fame has multiple output types : 
https://fame.readthedocs.io/en/latest/modules.html#writing-a-processing-module , but that doesn't really feel like stoQ

strelka doesn't seem to support it either, but that project is not really intended at manual analysis automation

**Comment by mlaferrera** [comment]
HI @chemberger -- sorry for the delay in getting back to you and thanks for the feedback. I think this is a great idea. You are right, the best way would be to add an option to the `PayloadMeta` object, similar to `should_archive`. Perhaps `should_scan` is a good option. This should be an easy addition for stoQ v2.

If you are interested in doing this, that would be terrific. Otherwise I think it is definitely a worthy feature and I'll add it to my todo list. Unfortunately it may be a few weeks with my schedule right now though.

**Comment by mlaferrera** [comment]
Hi @chemberger -- I just pushed up some [code](https://github.com/PUNCH-Cyber/stoq/tree/should_scan) that I believe implements this solution.

Essentially, when you are creating a payload (be it extracted or not), you can now set a `should_scan` flag. For example `PayloadMeta(should_scan=False)`. This will then tell stoQ to not send that payload to the worker plugins, but it will still log that the payload exists, and also allow you to archive the payload if `should_archive=True`. Please take a look at it and let me know your thoughts.

**Comment by mlaferrera** [comment]
This has been implemented in v3 dev.

**Comment by chemberger** [comment]
Hey, sorry for the late response. Thank you a bunch, I will try it out !
