### ISSUE TITLE
Version information

### ISSUE THREAD

**Issue by ytreister** [PUNCH-Cyber/stoq#122]
We implemented something for each plugin that I thought @mlaferrera might be interested in implementing in core stoQ.

Essentially, each plugin has a public method named `version_info()`.  This method will return the version info in the plugin.stoq configuration file at a minimum, but if the plugin has any other version information that could be useful, it provides that as well.

For example, a plugin that calls exiftool could have a method that looks like this:
```python
def version_info(self)
  version_info = {}
  version_info.update({'PluginVersion': self._plugin_version}) # From .stoq file
  version_info.update({'ExifToolVersion': self._get_exiftool_version()}) # From 3rd party tool (must write this private method)
  return version_info 
```
We are constantly updating our plugins, or the 3rd party tools that they call.  For example for OPSWAT, the version information is extensive and has when the definitions of each AV scanner were updated.  Having all of the version information available could make it helpful to understand why results of scanning the same payload could change over time as plugins/3rd party tools get updated.

We then have a decorator plugin that looks at the list of plugins run in the results, and loops over this list and calls the version_info method once per plugin that ran and compiles this into an object with all of the version information for all plugins ran during the scan.

**Comment by mlaferrera** [comment]
That's a really good idea. Would you be interested in doing a PR for it?

**Comment by ytreister** [comment]
I made the modifications to core stoq.  I also created a sample of how to use it in the stoq public plugin repo for a single plugin, exif.  I would think a version decorator could be created in the stoq public repo which would gather all of the version information and present it.

Let me know what you think.

**Comment by ytreister** [comment]
@mlaferrera I created a PR, but closed it before it got merged and can't figure out how to reopen it...

**Comment by mlaferrera** [comment]
It looks like the branch in your fork has been deleted, so the PR (#123) cannot be reopened.

I think I may have misunderstood how you planned on implementing this feature. I like the idea of adding functionality for specific version information to the results. I'm not sure mixing the functionality between the core framework and having to rely on a decorator plugin is the way to go. This could probably be done entirely as a decorator plugin, without any changes to the core framework.

**Comment by ytreister** [comment]
OK, sounds like a plan.  The decorator will loop over each plugin that ran and list the version_info for each plugin...  This issue should probably be part of the plugin repo...

**Comment by ytreister** [comment]
I thought about this a bit more.  What is nice about putting it into the core, is that all plugins will automatically at least have the stoq version info without any work.  A user does not need to overload and create a version_info method.  If not, then each plugin that wants to define version_info will have to have the additional line: 
```python
        if config.has_option("Documentation", "Version"):
            self._version_info.update({"PluginVersion": config.get("Documentation", "Version")})
```

**Comment by mlaferrera** [comment]
I see your point. If this is implemented, I think we may need to create a new class, such as `VersionInfo` or something to bake this in the core framework. That way we can ensure that the formatting of it is standardized within the results object.

**Comment by ytreister** [comment]
OK, I will start a branch in my fork and propose something...

**Comment by ytreister** [comment]
Hi @mlaferrera I thought of another use case.  Sometimes I have plugins that can take a while to execute but the results are predictable and do not change often.  They would potentially change if the version of the plugin or 3rd party tool, or data file from a 3rd party tool was updated.

In these cases, I could store the results along with version_info in a database and the plugin can first try and grab results from the database before trying to analyze the file.  The logic would be as follows:
```python
async def scan(...):
# Get payload MD5 and plugin version_info
# Attempt to get results from database (DB schema will have "results JSON", "version_info" and "MD5")
# If results received and version_info is identical, use them and return them
# If database query failed, new file never seen before, or version_info does not match: run the plugin to generate the results
# Attempt to update database with new results
# Return these results
```

**Comment by ytreister** [comment]
Going to close this issue, since there is not a great way to get this done.
