### ISSUE TITLE
Payload objects without content, but references to content

### ISSUE THREAD

**Issue by ytreister** [PUNCH-Cyber/stoq#135]
I would like to propose either a new payload class or enhancement to the existing payload class. Currently, I need to specify the payload's content in Payload.content and I can specify filename and anything else that I want in the PayloadMeta's extra_data dictionary.

Sometimes, I would prefer to specify a reference to content that may be stored on the file system or perhaps a NoSql database etc.

I know that there are archivers that could sort of be used for this purpose, but I do not think it really is meant for the purpose I am intending.

It would be nice if stoQ would natively support such a system.

For example suppose my plugin generates a file that I want to pass to the stoQ queue as an extracted payload, but I do not want to read the content and add the content directly to the Payload object.

It would be nice if I can do something like:
```python
# in my worker plugin's scan method the following file gets created: /path/to/myfile
extracted_payload = ExtractedPayload(content=ReferenceContent(path='/path/to/myfile'), PayloadMeta(extra_data='myfile'))
return WorkerResponse(results=results, extracted=extracted_payload)
```
In my example above ReferenceContent allows the user to specify where the payload could get the content from.  I would want ReferenceContent class to be flexible to allow retrieving the content from a number of sources.

Perhaps ReferenceContent could be a base class and the user could create their own children classes:
* FileSystemReferenceContent
* MongoDbReferenceContent
* etc.

The ExtractedPayload would eventually turn into a Payload object.  The payload object should work in a way so that payload.content returns the content regardless if it was set with reference or not.

This may mean that content would need to be a private member variable, and the user would need to use payload.get_content() or payload.set_content() to set the content.

If you like this idea, I am open to further discussions for details on such a design.

**Comment by ytreister** [comment]
Let me give you an example of where a reference could be useful.  Suppose you wanted to scan a file with exiftool and trid.  Both of these tools require your file to be on disk.  Currently both plugins would receive their payload and then write the content to disk.  it would be nice if they could reference a file on disk and eliminate duplicate writing of the file to disk.  if you had a very large payload and many plugins that require the payload be written to disk, this could save lots of processing time.

**Comment by mlaferrera** [comment]
Thanks for the feedback @ytreister. I believe I understand what you are proposing above. Can you provide a bit more insight into how you are using stoQ? That would really help to contextualize the concept. I'm happy to talk offline if you'd rather not talk publicly about your setup.

**Comment by ytreister** [comment]
contact me: ytreister@gmail.com

**Comment by mlaferrera** [comment]
Thanks for talking @ytreister . You make a fair point about writing a payload multiple times for plugins that call a command line executable. The solution you propose will become extremely complicated very quickly and I'm not sure is the is best path forward, especially in a distributed environment. I'm certainly open to talking more if you would find it beneficial.

With that, for the v3 plugins, I've updated exif and xorsearch to use STDIN for the payload. This will eliminate the need for the payloads to be written to disk into a temporary file. The payload content will essentially be piped into the executables via STDIN. I may end up doing the same for the decompress plugin, I just need to do a bit more testing with the various executables to ensure there aren't any issues doing the same. The only other plugin that won't be able to get updated is trid, solely because it doesn't support STDIN.

Thanks again for the feedback!

**Comment by ytreister** [comment]
I think updating those exif and xorsearch plugins was a great idea.  I agree that my proposed solution is probably too complicated, but i just wanted to present you one more example to think about.

Some plugins produce extracted payloads on diskspace.  For example 7zip might extract a zip file and the children are written to disk.  The plugin would then have to read the content to create an extracted payload.
Rather than having to read the file into memory right away, it might make sense to keep a reference to the file on disk.  This may only be helpful for trid which does not allow reading from stdin.  Maybe other users have other tools that do not support stdin.

I am thinking of the consequences of having so many potential large payloads in memory.  There is obviously a tradeoff between reading from disk multiple times and having many payloads in memory.

Perhaps just adding a best-practices section for plugin documentation which discourages writing to temp when it can be avoided.

**Comment by mlaferrera** [comment]
Completely agree. We've had a few discussions about drafting a best practices document. I'll add this to the list of items to include.

Thanks again! Feel free to re-open if you want to discuss further.
