### ISSUE TITLE
Docker User Issues

### ISSUE THREAD

**Issue by malvidin** [PUNCH-Cyber/stoq#136]
When running `stoq scan` or `stoq run` with the the stoq user, permission is denied to `/home/stoq/.stoq/logs`.  This line creates the working folder for root, so that the stoq user cannot create the log file or write to it.
https://github.com/PUNCH-Cyber/stoq/blob/00d55810e34e93075bd83f391a314635406d04a7/Dockerfile#L12

This would create the parent folder with permissions for the stoq user, if there is need for the plugins folder to be owned by root. It also fixes a small issue where the group was added with the user name.
```
RUN groupadd -r $GROUP && useradd -r -g $GROUP $USER && \
    install -d $STOQ_HOME -o $USER -g $GROUP &&
    mkdir -p /home/$USER/.stoq/plugins
```

**Comment by mlaferrera** [comment]
Thanks, @malvidin ! I've updated the Dockerfile. I'm running everything through a few tests and fixing anything else that pops up. I'll push an update once I'm done.

**Comment by mlaferrera** [comment]
Merged and released as part of v3. Thanks again @malvidin !
