### ISSUE TITLE
TLD Download Handling - IOC Extract

### ISSUE THREAD

**Issue by malvidin** [PUNCH-Cyber/stoq#139]
When run offline, the `iocextract` TLD list download fails, which causes `iocextract` to fail.

It could be added in an `iocextract` setup script, or with a Dockerfile if a Docker container is used.  

For the Dockerfile, something like the following would work.
`ADD https://data.iana.org/TLD/tlds-alpha-by-domain.txt /home/stoq/.stoq/plugins/iocextract/`

I didn't find any other public plugins that included external resources that are downloaded only on first access.

**Comment by mlaferrera** [comment]
This isn't really a bug, but more something that is part of the design. I think it's still a good idea to add it to the Dockerfile. I pushed up a commit for that.

**Comment by malvidin** [comment]
I can open a new issue if needed, but the ADD command uses 600 permissions, so the stoq worker cannot read the file.
