### ISSUE TITLE
v2 > v3 Documentation

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq#142]
Some documentation of the changes that occurred between v2 and v3 would be nice.

Currently my script using stoQ only outputs...
"stoq: error: unrecognized arguments: -E pass-dispatch"

I'm guessing that's related to deep-dispatchers being deprecated, but it seems more than deprecation may have occurred since the params to use them are now missing.

From the source changes it seems various aspects of plug-ins have also changed significantly, so I fear all my custom plug-ins are likely to be broken. There seems to be some documentation here...
https://stoq-framework.readthedocs.io/en/latest/dev/upgrading_plugins.html#v2-to-v3
...but I'm unclear on things like what to do with my current Deep Dispatcher plug-in. I have the vague impression that due to "entire request state is passed to..." I can convert it to a standard dispatcher, but that's not clear.

**Comment by ytreister** [comment]
I am working on converting one of my deep-dispatchers to a regular dispatcher right now.  I am not 100% sure I am doing this properly.  I have a worker named filetype.  My dispatcher will add plugins based on the result of that worker.  If the results are in the payload.results.workers, then I return a dispatcher response, otherwise I do not return anything.  Is that how I am supposed to do this?
```python
async def get_dispatches(self, payload: Payload, request: Request) -> Optional[DispatcherResponse]:
  filetype_results = payload.results.workers.get('filetype')
  if filetype_results:
    plugin_names = self._get_plugins_from_filetype_results(filetype_results)
  return DispatcherResponse(plugin_names=plugin_names)
```

**Comment by mlaferrera** [comment]
A full change log is available in the release notes, as well as the [CHANGELOG](https://github.com/PUNCH-Cyber/stoq/blob/master/CHANGELOG.md). The plugin documentation linked above shows all of the changes for each plugin class that must be made for them to work in v3. 

You're correct regarding using the `Request` object. Because of this, there was no longer a need for deep dispatchers, so we removed them. I agree, the documentation could be clarified to make that point. I'll work updating the docs.

**Comment by ytreister** [comment]
My log shows:
```
[2020-03-24 09:00:19,566 DEBUG] stoq: Starting scan of 1 tasks, deferring 0 to future rounds
[2020-03-24 09:00:19,567 DEBUG] stoq: Scanning Payload 03e064a9-912d-481e-a601-635e5a59f45e with WorkerPlugin filetype
[2020-03-24 09:00:25,610 DEBUG] stoq: Completed scan of 03e064a9-912d-481e-a601-635e5a59f45e with 15 result keys, 0 additional dispatches, and 0 extracted payloads
[2020-03-24 09:00:25,612 DEBUG] stoq: Beginning worker round 2
[2020-03-24 09:00:25,613 DEBUG] stoq: Sending 03e064a9-912d-481e-a601-635e5a59f45e to dispatcher (filetype_dispatcher)
```
Will the scans indefinetely try until the DispatcherResponse gets returned?

**Comment by mlaferrera** [comment]
@ytreister you'll want to ensure that `plugin_names` is defined, even if there are no results. As is, that code will raise an exception if `filetype_results` is empty. But yes, it looks like the code will work fine.

It won't run indefinitely. Each payload should be sent to each dispatcher only once.

**Comment by Kolano** [comment]
> WorkerPlugins now have a configuration option of required_workers. This allows for chained worker dependencies. If required_workers is defined, the parent plugin will not be run until all required plugins are completed successfully. The parent plugin may then use results from other completed plugins for their respective scanning tasks.

What about required worked for Dispatcher plugins?

Do those still need to be handled as in v2...

```
		if not (any("clamav" in plugins for plugins in payload.worker_results) and any("hash" in plugins for plugins in payload.worker_results) and any("mimetype" in plugins for plugins in payload.worker_results) and any("trid" in plugins for plugins in payload.worker_results)):
			raise StoqPluginException("pass-dispatch requires results from the following plugins: clamav, hash, mimetype, and trid.")
```

**Comment by ytreister** [comment]
Sorry, I had bad indentation when I copied and simplified my code from my IDE to post to github.  My return was inside the if.  I want to make sure that this is proper behavior.  I do not return anything if my worker plugin `filetype` does not have results.  If `filetype` has results, I then get plugin_names and return a `DispatcherResponse`.

On a related note, it is not 100% clear to me if the add_start_dispatch option from Stoq.run() runs for each payload or only for payloads added to the queue by a provider.  I had the following code:
```python
s = Stoq(
 providers=['dirmonitor'],
 always_dispatch=['filetype'],
 dispatchers=['filetype_dispatcher']
)
loop = asyncio.get_event_loop()
loop.run_until_complete(s.run())
```
and was thinking of changing to:
```python
s = Stoq(
 providers=['dirmonitor'],
 dispatchers=['filetype_dispatcher']
)
loop = asyncio.get_event_loop()
loop.run_until_complete(s.run(add_start_dispatch=['filetype']))
```
But it is not clear if extracted payloads would automatically have the `filetype` worker plugin run if I did this.

**Comment by ytreister** [comment]
@Kolano 
> What about required worked for Dispatcher plugins?

I agree, it seems like dispatcher plugins should be allowed to define required workers before trying to dispatch.  This is not critical, since you can do an if like I posted above and just wait until 2nd round.

**Comment by Kolano** [comment]
Also this change seems to require some coverage in the v2>v3 notes:

> Payload.worker_results has been removed in favor of PayloadResults.workers

**Comment by mlaferrera** [comment]
@ytreister `add_start_dispatch` will only send the very first payload to the defined plugin(s), and  `always_dispatch` will send every payload, to include extracted payloads, to the defined plugin(s). In the latter example code above, the `filetype` plugin will only run on the initial payload. The former example, it will run on all payloads, to include extracted ones.

**Comment by mlaferrera** [comment]
@Kolano required plugins is a feature of worker plugins only. This feature essentially allow workers to dispatch. There isn't really a need for them within Dispatcher plugins, because they already have the ability to dispatch to other worker plugins.

**Comment by Kolano** [comment]
> @Kolano required plugins is a feature of worker plugins only. This feature essentially allow workers to dispatch. There isn't really a need for them within Dispatcher plugins, because they already have the ability to dispatch to other worker plugins.

Perhaps, but it would make the handling of such more consistent across things. I have ~30 lines of code that could be reduced by 2/3s if I could guarantee worker datasets were in place when then needed to be.

**Comment by mlaferrera** [comment]
Considering the complexity that would be required within the core framework, I don't see this happening in the v3 release cycle. Perhaps we can revisit this in a future major release. I definitely appreciate the feedback!

**Comment by Kolano** [comment]
There may be a typo in the changelog...

> Payload.plugins_run moved to PayloadResults.plugins_runs and is now a Dict[str, List[str]] rather than Dict[str, List[List[str]]]

Should that say Payload.results.plugins_runs ?

And elsewhere we have "plugins_run", so unclear if that was intended to be pluralized.

**Comment by mlaferrera** [comment]
Thanks, @Kolano . I just pushed up a fix for some of the typos in the CHANGELOG.
