### ISSUE TITLE
Add cchardet to framework requirements

### ISSUE THREAD

**Issue by malvidin** [PUNCH-Cyber/stoq#151]
Recommend adding cchardet to the requirements to support beautifulsoup4.
beautifulsoup4 prefers cchardet, but falls back to chardet if it is not available.
`cchardet~=2.1.5`
https://github.com/PUNCH-Cyber/stoq/blob/53daf12bcc13714504aabc150cace0dc0e6f4305/requirements.txt#L1

The UnicodeDammit class from bs4 is used in the stoq framework, and in many of the public plugins.

**Comment by mlaferrera** [comment]
One of the goals is to limit requirements for the core framework, so I'd rather not add another one. We can make a note in documentation though.
