### ISSUE TITLE
StoqConfigParser class is not part of stoq.helpers when using pip3 install stoq-framework to install stoq.  To reproduce, follow the installation instructions in the documentation, install a plugin through the 'from directory' option and attempt to run stoq scan <some file>.  The code in the master branch is correct but not when installed using  pip3.

### ISSUE THREAD

**Issue by deadh4nd** [PUNCH-Cyber/stoq#154]
**Describe the bug**

**To Reproduce**
2. See error

**Expected behavior**

**Client (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - stoQ Version [e.g. v2.0.0]

**Exception**
If applicable, the full exception traceback

**Additional context**

**Comment by mlaferrera** [comment]
I'm not sure I follow. Are you saying that `StoqConfigParser` is not in `stoq.helpers` when you install with `pip3 install stoq-framework`? What version of stoQ are you installing? What operating system are you on?

**Comment by deadh4nd** [comment]
Hey Marcus,

Good morning sir.  Hope you’re doing well and thanks for reaching out.  So yes, the StoqConfigParser class is not in stoq.helpers when i install with pip3 install stoq-framework.  I am installing version 3 of the stoq framework and I’m on an Ubuntu server 18.04 OS.  I ended up copying the source to disk and installing that way.  The pip3 installation method just wasn’t working for me.  Figured others were probably running into the same issue and that it might turn them off from using the framework (which I don’t want to see happen).  Please let me know if you have any more questions and I’ll be happy to answer them.  Anything to help sir!

Best Regards,

-Joseph Silva

**Comment by mlaferrera** [comment]
Hi @deadh4nd - Unfortunately I am unable to replicate this. Can you try running `pip3 install --upgrade stoq-framework` or `pip3 install stoq-framework==3.0.0` and see if that works for you? It sounds like there may be some conflicts from a older version of stoQ that are causing some issues.

**Comment by deadh4nd** [comment]
Hey Marcus,

Sure.  I’ll have to create a new VM to test this on (since I already have a working copy on my current server), but I should be able to get back to you later today if that’s cool.  

-Joseph

**Comment by deadh4nd** [comment]
Hey Marcus,

Work is getting in the way at the moment.  But as soon as I have some time I’ll give it a shot.  Sorry for the delay sir.

-Joseph

**Comment by deadh4nd** [comment]
Hi Marcus,

So I tried both of the pip3 installation methods you described and got the same error both times: “Could not find a version that satisfies the requirement stoq-framework (from versions: )  No matching distribution found for stoq-framework.”  That being said I’m also testing in my lab environment, so let me try on a system in a different environment and see if that fixes things.  I’ll get back to you with the results of that test tomorrow.  Thanks for taking the time to help me with this issue.

Best Regards,

-Joseph

**Comment by deadh4nd** [comment]
Hey Marcus,

Good morning sir.  You can close this out.  I’m sorry for the inconvenience.  Looks like there is something going on in my lab.  Once I’m on a system outside of it, the installation works as expected.  Now to hound down what’s going wrong on my end.  

Also, just switched to V3 and damn sir.  I am LOVING the fact that I can now chain workers together in a specific order.  That was something that I was struggling with in V2 and it makes a huge improvement to workflows.  

Best Regards,

-Joseph

**Comment by mlaferrera** [comment]
Awesome! Great to hear v3 is benefiting your workflow. Let us know if you run into any other issues.
