### ISSUE TITLE
The future of stoQ

### ISSUE THREAD

**Issue by ytreister** [PUNCH-Cyber/stoq#157]
I was in a meeting recently were someone told me that @mlaferrera no longer works at PUNCH Cyber.  Does anyone know if that is true, and if so what the future of this framework might be?  Does PUNCH plan to maintain this repo?

**Comment by mgeide** [comment]
PUNCH will continue to maintain the repo- focusing on keeping the stoq core stable and addressing bug fixes and versioning issues to support the stoq community. Please continue to submit bug and pull requests.
New features and plugin requests will be considered on a case-by-case basis; additionally, PUNCH is able to provide consultative and development services to develop private/custom plugins and address deployment/integration needs for customer use-cases and workflows.
