### ISSUE TITLE
After fresh clone, install.sh does not retain correct permissions

### ISSUE THREAD

**Issue by deadbits** [PUNCH-Cyber/stoq#32]
```
intelstream /opt/stoq ‹master› » ./install.sh
zsh: permission denied: ./install.sh
```

This is immediately after a fresh install via git clone into a directory owned by `root` at `/opt/stoq`, and I am running as the user `root`. There is no execute bit set on the file. Setting this file to `chmod +x install.sh" allows execution, ofc.

Should this be included into the repo it's part of the default install process?

**Comment by mlaferrera** [comment]
Thanks! I've updated the documentation to be more explicit (fa4a802) on how to run the install script.
