### ISSUE TITLE
sdist asset on releases page

### ISSUE THREAD

**Issue by awillis** [PUNCH-Cyber/stoq#45]
Would you consider adding a pip installable package on the releases page? Preferably an sdist and not a bdist? You should have the option to attach additional assets when you create a release.

**Comment by mlaferrera** [comment]
I'm certainly not against it, just need to figure out a name that doesn't conflict with the current pip. stoq-framework perhaps?

**Comment by awillis** [comment]
Stoqq?

**Comment by mlaferrera** [comment]
I'm closing this since v2 has a [PyPi](https://pypi.org/project/stoq-framework/#description) package available
