### ISSUE TITLE
Save to specific file

### ISSUE THREAD

**Issue by ShimonKlein** [PUNCH-Cyber/stoq#7]
I am having trouble saving results from Iocextract to a specific file. I would like to specify the file it should write results to. As of now I am using the following command:  "./stoq-cli.py iocextract -F ingest/myfile -C file" However I cant seem to figure out how to specify where to save to. 

Another thing I am unsure about is to use Iocextract for all files within a directory. Ideally I would like to have it process all files within a directory and then have all the results written to one file with the time-stamp appended to the file name. Is that possible?

**Comment by mlaferrera** [comment]
Hi ShimonKlein,

Currently, there is not a means to specify the output file. The results will be placed in ```results/$plugin_name``` with a randomly generate filename. You can change the default directory by updating ```results_dir``` configuration setting in ```stoq.cfg```.

To scan an entire directory, you can simply run ```./stoq-cli.py iocextract -F path/to/your/directory -C file```. This however will not place all results into one file, but instead, one randomly named file per result.

I'll tag this issue as an enhancement and see if we can get something similar to your request implemented.

**Comment by ShimonKlein** [comment]
Thank you! That would be a great help.

**Comment by mlaferrera** [comment]
@ShimonKlein, I believe your issue should now be supported. Please let me know if you run into any issues.
