### ISSUE TITLE
stoq-cli.py help menu

### ISSUE THREAD

**Issue by redlazarus** [PUNCH-Cyber/stoq#9]
Suggest a language clarification/addition to the --help language of stoq-cli.py.  

It is possible to get help on a specific plugin using --help after loading the plugin. 

Recommended language:

For help on a specific plugin, the plugin can be loaded and --help or -h switch can be used to receive additional information 

for additional details on the iocextract plugin, type the following command:
stoq-cli.py iocextract --help

**Comment by mlaferrera** [comment]
Added an example when calling stoq-cli.py -h in d628b36
