### ISSUE TITLE
Connector Failure Breaks All Connector

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq#93]
**Is your feature request related to a problem? Please describe.**
It seems that if exceptions occur with one Connector plug-in's output, output of others also fail (perhaps dependent on their process order). For instance, given this command...
`stoq scan file -a hash -C es-search stdout filedir`
...an exception with the es-search plugin causes the stdout and filedir outputs to not be processed (or perhaps also fail).

**Describe the solution you'd like**
Connectors should be handled independently, so that a failure on one will not cause others to fail.

**Comment by mlaferrera** [comment]
Thanks again @Kolano. The latest push handles connector plugin exceptions gracefully. Feel free to reopen if you find issues.
