### ISSUE TITLE
Documentation Issues: Core-Individual Scan

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq#94]
**Describe the bug**
There are a bunch of issues with the initial example provided here...
https://stoq-framework.readthedocs.io/en/latest/dev/core.html#individual-scan

- A custom stoq() object is defined in step 3, but then in step 4 it's overwritten.
`s = Stoq()`
- "plugins" undefined (Not sure, but I think the "add_start_dispatch" should just be omitted?)...
```
     results = s.scan(
             content=src_payload.read(),
             request_meta=meta,
             add_start_dispatch=plugins)
```

- Revising those results in this script...
```
from stoq import Stoq

workers = ['hash']
plugin_dirs = ['/opt/plugins']

s = Stoq(
	plugin_dir_list=plugin_dirs,
	always_dispatch=workers
)

src = '/tmp/bad.exe'
with open(src, 'rb') as src_payload:
	s = Stoq()
	meta = {'filename': src}
	results = s.scan(
		content=src_payload.read(),
		request_meta=meta
	)
print(results)
```

- With revisions to account for alternate plug-in and analyzed file locations on my system I get the error...
```
Traceback (most recent call last):
  File "analyze.py", line 17, in <module>
    request_meta=meta
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/utils.py", line 57, in ratelimit
    return func(*args, **kwargs)
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/core.py", line 479, in scan
    payload, request_meta, add_start_dispatch, add_start_deep_dispatch
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/core.py", line 516, in scan_payload
    payload, add_dispatch, add_deep_dispatch, request_meta
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/core.py", line 724, in _single_scan
    if request_meta.archive_payloads and payload.payload_meta.should_archive:
AttributeError: 'dict' object has no attribute 'archive_payloads'
```

- This is against stoQ :: v2.0.2, You may want to update the Bug submission template to ensure a version is captured with each submission.

- It would be nice to use an alternate format for sample source code allowing for direct cut-n-paste, stripping the ">>>" and "..." from lines can be a pain.

**Comment by mlaferrera** [comment]
Thanks for the documentation review! I've corrected the docs.

As a side note, I highly recommend using ipython3 rather than straight up python if you plan on copy/pasting examples. You'll be able to copy and paste directly from the documentation that way.

**Comment by Kolano** [comment]
OK, on ipython3, but it still may be best to not make presumptions about the development environments of others and just provide unformatted code; or at least outline the need for ipython3 under...
https://stoq-framework.readthedocs.io/en/latest/installation.html#dev-environment
