### ISSUE TITLE
Reinstalling an already existing plugin does not raise an error

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq#99]
**Describe the bug**
I'm having trouble getting a custom DeepDispatcher working. I see similar errors trying to use the vt-search's DeepDispatcher so I'll describe that.

**To Reproduce**
1. stoq scan file -E vt-search
2. See exception

**Expected behavior**
No error. Since iocextract wasn't run before hand, standard no plug-in output.

**Client (please complete the following information):**
 - OS: Ubuntu 18.10
 - stoQ Version v2.0.3

**Exception**
```
Traceback (most recent call last):
  File "/home/pass/.stoq/.venv/bin/stoq", line 11, in <module>
    sys.exit(main())
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/cli.py", line 261, in main
    plugin_dir_list=args.plugin_dir,
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/core.py", line 431, in __init__
    d: self.load_plugin(d) for d in deep_dispatchers if d
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/core.py", line 431, in <dictcomp>
    d: self.load_plugin(d) for d in deep_dispatchers if d
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/plugin_manager.py", line 109, in load_plugin
    module_path, plugin_config = self._plugin_name_to_info[plugin_name]
KeyError: 'vt-search'
```

**Comment by mlaferrera** [comment]
That error is saying that it can't find a `vt-search` plugin. I believe you are referring to `vtmis-search`. If you change your command to include that (so long as it is installed) it should run as expected.

**Comment by Kolano** [comment]
Yeah, sorry. `KeyError: <plugin name>` isn't too helpful, a more descriptive exception there would be nice.

The similar error seen from my plugin seems to have been that I forgot to use the --upgrade switch on install, and had continued to use a broken iteration. I'm a little unclear why the extra switch is necessary, it might be good to provide a warning message there if a pre-existing plug-in exists.

**Comment by mlaferrera** [comment]
The `--upgrade` command implies you are upgrading the plugin. If you run `stoq install` without the `--upgrade` option, it will return an error letting you know the plugin already exists. If you still want to install the plugin you should do so with `--upgrade`. If you use `--upgrade` it will overwrite all of the plugins files, essentially reinstalling it if it's the same version. You can then run `stoq list` to view what plugins are available, along with their version.

**Comment by Kolano** [comment]
But that's not what happens, the install command without --upgrade still provides the "Successfully installed to ..." message.

**Comment by mlaferrera** [comment]
I'm going to need more than that to troubleshoot, preferably code. I just attempted to install a plugin using `--upgrade` and there are no issues. It overwrites the previous plugin.

**Comment by Kolano** [comment]
But you had said it would error if "--upgrade" isn't used and it doesn't it says it's installed sucessfully even though no overwrite occurs in that case.

**Comment by mlaferrera** [comment]
Please provide code examples.

**Comment by Kolano** [comment]
You can use your own code. Specifically...
`stoq install ./vtmis-search`
...if run against an install with vtmis-search previously installed, results in...
`Successfully installed to /home/user/.stoq/plugins`
...even though no installation occurs in that case. No error is output.

**Comment by mlaferrera** [comment]
I see what you're saying. You're right, it doesn't appear to error out if the plugin already exists and no changes are made. I'll see what I can do to change that behavior in a future release.

**Comment by Kolano** [comment]
Thanks. A more descriptive error when using a non-existent plug-in would also be nice.

**Comment by Kolano** [comment]
One other unrelated query...

The vtmis-search plugin's deep dispatcher tests for worker data like...
`'iocextract' in payload.worker_results`
...but the worker "scan" function tests like...
```
for worker_result in payload.worker_results:
            if 'iocextract' in worker_result:
```
In my custom plug-in I'm unable to test like the vtmis-search plugin's deep-dispatcher because my worker_results is an array of objects, so it seem to require the later style to do so.

What determines if worker_results is an array and won't support the simple "in" test?

**Comment by mlaferrera** [comment]
Please open another ticket for this so the conversation doesn't get too convoluted.
